import { Category, TestResult } from './runner';

const ORDER: Category[] = [
    'DIFF', 'LUA_CRASH', 'LUA_COMPILE_FAIL', 'MATCH', 'NONDET', 'NODE_FAIL'];

const MEANING: { [key: string]: string } = {
    MATCH: 'lua stdout equals node stdout',
    DIFF: 'both ran, outputs differ - a jslib behaviour bug',
    LUA_CRASH: 'lua.exe errored or timed out',
    LUA_COMPILE_FAIL: 'tsc-lua threw, or emitted nothing',
    NODE_FAIL: 'does not run under node either - excluded, not a jslib finding',
    NONDET: 'node output not reproducible - excluded'
};

// a line-oriented diff is enough here: these outputs are short, and the point is to show
// what changed rather than to minimise the edit script
function renderDiff(expected: string, actual: string): string[] {
    const expectedLines = expected.split('\n');
    const actualLines = actual.split('\n');
    const lines: string[] = ['```diff'];

    for (let i = 0; i < Math.max(expectedLines.length, actualLines.length); i++) {
        const e = expectedLines[i];
        const a = actualLines[i];
        if (e === a) {
            lines.push('  ' + (e === undefined ? '' : e));
        } else {
            if (e !== undefined) { lines.push('- ' + e); }
            if (a !== undefined) { lines.push('+ ' + a); }
        }
    }

    lines.push('```');
    return lines;
}

export function renderReport(results: TestResult[]): string {
    const lines: string[] = [
        '# jslib conformance report',
        '',
        'Generated by `npm run conformance`. Node is the oracle: `-` is what node printed,',
        '`+` is what jslib printed.',
        '',
        '## Summary',
        '',
        '| Category | Count | Meaning |',
        '| --- | --- | --- |'
    ];

    ORDER.forEach((category: Category) => {
        const count = results.filter((r: TestResult) => r.category === category).length;
        lines.push('| ' + category + ' | ' + count + ' | ' + MEANING[category] + ' |');
    });

    lines.push('', 'Total: ' + results.length + ' tests.', '');
    lines.push('## Standing findings', '');
    lines.push('- jslib\'s `console.log` separates arguments with a tab where node uses a');
    lines.push('  space, and renders arrays through `join(\',\')` where node uses `inspect`.');
    lines.push('  The node side is adapted down to jslib\'s format, so it does not appear as');
    lines.push('  a diff below. `console.log(undefined)` crashes jslib outright.');
    lines.push('');

    ORDER.forEach((category: Category) => {
        const inCategory = results.filter((r: TestResult) => r.category === category);
        if (inCategory.length === 0) {
            return;
        }

        lines.push('## ' + category + ' (' + inCategory.length + ')', '');

        inCategory.forEach((r: TestResult) => {
            lines.push('### ' + r.name, '');

            if (r.category === 'DIFF') {
                renderDiff(r.nodeStdout, r.luaStdout).forEach((l: string) => lines.push(l));
                lines.push('');
            } else if (r.detail) {
                lines.push('```text', r.detail.replace(/\s+$/, ''), '```', '');
            }
        });
    });

    return lines.join('\n');
}
